autocommit

diff --git a/.bin/backup b/.bin/backup
--- a/.bin/backup
+++ b/.bin/backup
@@ -1,17 +1,26 @@
 #!/usr/bin/env bash
 
+usage() { echo -e "Usage:\t$(basename "$0") -s <source> -d <destination>" && exit 1; }
+[ $# -eq 0 ] && usage
+
+while getopts ":hs:d:" opt; do
+  case $opt in
+  s) src=$OPTARG ;;
+  d) dst=$OPTARG ;;
+  h | *) usage ;;
+  esac
+done
+
 HDD="/media/$USER/HDD"
-src=$1
-dst=$2
+[ -d "$HDD" ] || {
+  echo "Can't find external drive \"$HDD\""
+  exit 1
+}
 
-if [ ! -d "$HDD" ]; then
-	echo "Can't find external drive \"HDD\", try again" && exit 1
-fi
-
-rsync --dry-run -ahPuvz --delete-after "$HOME/$src/" "$HDD/$dst/"
+rsync "$HOME/$src/" "$HDD/$dst/" --dry-run -ahPuvz --delete-after
 read -rp "Do you want to proceed with that? (y|n): " proceed
 if [ "$proceed" = "y" ]; then
-	rsync -ahPuvz --delete-after "$HOME/$src/" "$HDD/$dst/" && echo "Done"
+  rsync "$HOME/$src/" "$HDD/$dst/" -ahPuvz --delete-after && echo -e "\nDone"
 else
-	echo "Backup aborted"
+  echo -e "\nBackup aborted"
 fi
diff --git a/.bin/mp4tomkv b/.bin/mp4tomkv
--- a/.bin/mp4tomkv
+++ b/.bin/mp4tomkv
@@ -1,17 +1,19 @@
 #!/usr/bin/env bash
 
-set -e
+usage() { echo -e "Usage:\t$(basename "$0") <dir1> [... <dirN>]" && exit 1; }
+[ $# -eq 0 ] && usage
 
-dir=$1
+dirs=("$@")
 
-if [ ! -d "$dir" ]; then
-	echo -e "Usage:\t$(basename "$0") <directory>" && exit 1
-fi
+for dir in "${dirs[@]}"; do
+	# exit on fail
+	[ -d "$dir" ] || usage
 
-pushd "$dir" || exit 1
-for video in ./*.mp4; do
-	ffmpeg -i "$video" \
-		-c:v libx264 -crf 40 -filter:v fps=fps=10 -c:a libopus -application voip -ab 16k -ac 1 -cutoff 12000 \
-		"$(echo "$video" | sed 's/mp4/mkv/')"
+	pushd "$dir" || continue
+	for vid in ./*.mp4; do
+		ffmpeg -i "$vid" \
+			-c:v libx264 -crf 40 -filter:v fps=fps=10 -c:a libopus -application voip -ab 16k -ac 1 -cutoff 12000 \
+			"$(echo "$vid" | sed 's/mp4/mkv/')"
+	done
+	popd || continue
 done
-popd || exit 1
diff --git a/.bin/videotime b/.bin/videotime
--- a/.bin/videotime
+++ b/.bin/videotime
@@ -1,27 +1,32 @@
 #!/usr/bin/env bash
 
-set -e
+usage() { echo -e "Usage:\t$(basename "$0") -d <dir1> [... <dirN>] -f <format>" && exit 1; }
+[ $# -eq 0 ] && usage
 
-optstr=":d:f:"
-dir=""
-fmt=""
-
-while getopts $optstr opt; do
+while getopts ":hd:f:" opt; do
   case $opt in
-  d) dir=$OPTARG ;;
+  d)
+    dirs=("$OPTARG")
+    # collect until another -opt is found, or no more -opt are left
+    until [[ $(eval "echo \${$OPTIND}") =~ ^-.* ]] || [ -z "$(eval "echo \${$OPTIND}")" ]; do
+      dirs+=("$(eval "echo \${$OPTIND}")")
+      OPTIND=$((OPTIND + 1))
+    done
+    for dir in "${dirs[@]}"; do
+      [ -d "$dir" ] || echo "Skipping invalid directory \"$dir\""
+    done
+    ;;
   f) fmt=$OPTARG ;;
-  ? | : | *) echo -e "Usage:\t$(basename "$0") -d <directory> -f <format>" && exit 1 ;;
+  h | *) usage ;;
   esac
 done
-
-if [ ! -d "$dir" ]; then
-  echo "\"$dir\" is not a valid directory" && exit 1
-fi
 
 tot_seconds=0
 
 i=1
-for vid in $(find "$dir" -name "*.$fmt" -exec realpath {} \;); do
+IFS=$'\n'
+# for vid in $(find "${dirs[@]}" -exec file -N -i -- {} + | sed -n 's!: video/[^:]*$!!p'); do
+for vid in $(find "${dirs[@]}" -name "*.$fmt" -exec realpath {} \;); do
   raw_time=$(ffmpeg -i "$vid" 2>&1 | rg "Duration: ([0-9]{2,}:[0-9]{2}:[0-9]{2})" -or '$1')
   seconds=$(echo "$raw_time" | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
   ((tot_seconds += seconds))
