autocommit

diff --git a/.bin/rcdrive b/.bin/rcdrive
--- a/.bin/rcdrive
+++ b/.bin/rcdrive
@@ -1,8 +1,19 @@
 #!/usr/bin/env bash
 
-path=~/uni/cybersec
-[ ! -d "$path" ] && { "Path \"$path\" not found, aborting."; exit 1; }
+usage() { echo -e "Usage:\t$(basename "$0") [-r]" && exit 1; }
 
-rclone sync "$path" cybersec: --exclude "video/**" --update --progress && \
-  echo -e "\nCleaning remote empty dirs..." && \
-  rclone rmdirs cybersec: --leave-root
+path=~/uni/cybersec
+[ ! -d "$path" ] && { echo "Path \"$path\" not found, aborting."; exit 1; }
+
+# -r for empty dirs only, no sync
+if [ $# -eq 1 ]; then
+  if [ "$1" = "-r" ]; then
+    echo -e "\nCleaning remote empty dirs..."
+    rclone rmdirs cybersec: --leave-root &
+    exit 0
+  else
+    usage
+  fi
+fi
+
+rclone sync "$path" cybersec: --exclude "video/**" --update --progress
diff --git a/.bin/rcmega b/.bin/rcmega
--- a/.bin/rcmega
+++ b/.bin/rcmega
@@ -7,11 +7,9 @@ dir=$1
 path=~/uni/cybersec/"$dir"
 
 if [[ "$dir" =~ ^[12]a[12]s$ ]]; then
-  [ ! -d "$path" ] && { "Path \"$path\" not found, aborting."; exit 1; }
+  [ ! -d "$path" ] && { echo "Path \"$path\" not found, aborting."; exit 1; }
 
-  rclone copy "$path" mega_am:cybersec/"$dir" --include "/**/video/**" --update --progress && \
-  echo -e "\nCleaning remote empty dirs..." && \
-  rclone rmdirs mega_am: --leave-root
+  rclone copy "$path" mega_am:cybersec/"$dir" --include "/**/video/**" --update --progress
 else
   usage
 fi
